name: Update Version File

on:
  push:
    branches:
      - main  # You can specify the branch you want this action to run on

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Get the latest commit hash
      id: commit_info
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Update version.txt with the latest commit hash
      run: echo "${{ steps.commit_info.outputs.commit_hash }}" > version.txt

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push version update
      run: |
        git add version.txt
        git commit -m "Update version.txt to latest commit hash"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
